module.exports = 'BYZ)LMV\n' +
    '2CT)GV2\n' +
    '6RK)HK7\n' +
    'RJJ)MVV\n' +
    'YFQ)4LC\n' +
    'Q58)D46\n' +
    'D4T)3X8\n' +
    '9GF)P89\n' +
    'TFP)9VJ\n' +
    '5J9)YYK\n' +
    'WKB)6B4\n' +
    'PM4)3G9\n' +
    'NRG)QDB\n' +
    'Y2X)464\n' +
    'T1S)MJ1\n' +
    'RQ8)PD6\n' +
    'XP7)3F2\n' +
    'Y4Q)65H\n' +
    'KBG)ZMM\n' +
    'PCT)H5K\n' +
    'YPG)NZ6\n' +
    '1KP)RFT\n' +
    '3Y7)ZN5\n' +
    'BYH)RWH\n' +
    '1BQ)X8J\n' +
    '1VJ)MWT\n' +
    'GHH)7NX\n' +
    'CWZ)WC1\n' +
    '5YB)3F5\n' +
    'YZG)NQJ\n' +
    '18F)VZV\n' +
    'Z6Z)ZX9\n' +
    'PT3)KWY\n' +
    'QR2)5QK\n' +
    'HQL)6LJ\n' +
    'JMG)S4N\n' +
    '4RL)PWG\n' +
    'G1H)J8W\n' +
    'WCX)RB3\n' +
    'CR4)GX5\n' +
    '4YN)BDT\n' +
    'ZQY)C8H\n' +
    'JRF)Y62\n' +
    'GPY)4RN\n' +
    '6TF)R8Y\n' +
    'JWD)L9L\n' +
    'QQ5)ZMX\n' +
    'YY5)JFY\n' +
    'F15)JCJ\n' +
    'J71)ZT8\n' +
    '9KF)JR8\n' +
    '82X)449\n' +
    '544)WKB\n' +
    'QRN)MKW\n' +
    'Y57)1KV\n' +
    '2C2)6C7\n' +
    'QNQ)MKH\n' +
    'X1H)XK6\n' +
    'QBH)GKH\n' +
    'FMY)9P9\n' +
    '7DZ)Q9L\n' +
    '8HP)F3V\n' +
    'XR9)4XS\n' +
    '9CP)25Q\n' +
    '4PC)92N\n' +
    '87B)C3N\n' +
    'FFW)1CY\n' +
    'DFH)3VC\n' +
    '4RS)PM4\n' +
    'LQF)J6P\n' +
    'ZXM)1K7\n' +
    'WYZ)C22\n' +
    'K1Y)YMZ\n' +
    'KXV)P93\n' +
    'K4G)MYZ\n' +
    'RWM)VC1\n' +
    'T8S)93S\n' +
    '21J)MHY\n' +
    'MF7)N4L\n' +
    '255)BDL\n' +
    '1MG)M4B\n' +
    'KJL)K7J\n' +
    'MLX)ZR7\n' +
    'COM)WWS\n' +
    'WPN)LRP\n' +
    'DQ6)9XW\n' +
    'DMF)RJ3\n' +
    'JNL)QMM\n' +
    '68T)QLS\n' +
    'NQ1)RP3\n' +
    '18C)7DC\n' +
    'KRH)2RT\n' +
    'KGT)DPL\n' +
    '99Q)SWR\n' +
    'KRP)DCW\n' +
    'Y3P)PCT\n' +
    'PZJ)2RN\n' +
    'FTY)R6J\n' +
    '7W2)T32\n' +
    '6ZZ)VZ3\n' +
    'DPL)7KV\n' +
    'VX2)NH8\n' +
    '2QF)GS5\n' +
    'Q8S)SZ4\n' +
    'VP4)8B8\n' +
    'S6X)BYZ\n' +
    'RKK)QQ5\n' +
    'LYN)S7C\n' +
    'ZZD)ZTP\n' +
    '59C)25M\n' +
    '3SD)KPS\n' +
    'GPY)5LY\n' +
    'B6Q)9M6\n' +
    'SDL)SGT\n' +
    'VY6)J47\n' +
    'KY6)WMB\n' +
    'M3Z)CWZ\n' +
    '287)6FY\n' +
    'JR8)5LP\n' +
    'DXG)8GP\n' +
    '5GV)Q15\n' +
    'WQ3)65V\n' +
    'MHY)ZTD\n' +
    '2KN)1LQ\n' +
    'FPF)7W2\n' +
    'NPB)6NL\n' +
    'T32)9TC\n' +
    'JTZ)YHM\n' +
    'VNT)QWK\n' +
    'GNZ)VBD\n' +
    'JCW)JRR\n' +
    'N2B)TVX\n' +
    'VF2)P38\n' +
    'V5Z)3W5\n' +
    'SST)9LZ\n' +
    'TRC)PYG\n' +
    '9VJ)SSX\n' +
    '8BD)TXH\n' +
    'WVM)XRV\n' +
    'Z5B)T93\n' +
    'Z5L)T7K\n' +
    'H1V)YOU\n' +
    'NKX)54Z\n' +
    '4XS)DZK\n' +
    'D3V)S4K\n' +
    'Q62)FWW\n' +
    'SWD)DJT\n' +
    '2MJ)MXT\n' +
    '98J)17N\n' +
    'GDZ)YN6\n' +
    'DRP)4PC\n' +
    '4L3)VNG\n' +
    'R7G)7M9\n' +
    'WX5)MFM\n' +
    '2S9)BK5\n' +
    'N9H)FDR\n' +
    '22T)Y3Y\n' +
    'L65)XLK\n' +
    '3DJ)S18\n' +
    'S18)WHR\n' +
    'S1Q)GYH\n' +
    'BF9)99R\n' +
    'CDW)MB6\n' +
    'FF7)44W\n' +
    '5X7)XSL\n' +
    'QG3)WC8\n' +
    '6Q4)83D\n' +
    'LP6)NTH\n' +
    'V84)X6W\n' +
    'SGR)FFW\n' +
    'CVX)54C\n' +
    '6KD)RML\n' +
    'KZV)JRY\n' +
    'KY5)W9D\n' +
    'L4N)38R\n' +
    'GVD)KXQ\n' +
    'RCK)XNX\n' +
    'XRV)TKH\n' +
    '5JZ)G19\n' +
    'Q5V)7VD\n' +
    'FYK)2MQ\n' +
    'VKV)8ZL\n' +
    'YQM)6XF\n' +
    'DKB)SND\n' +
    'HMZ)689\n' +
    'W2S)2YB\n' +
    'SWR)ZZD\n' +
    'MGQ)TW3\n' +
    '3Y5)HHP\n' +
    'DJT)H7L\n' +
    'VNV)HMZ\n' +
    'C11)PWB\n' +
    'M3Z)SZ2\n' +
    'DHF)QG3\n' +
    'J9D)LQF\n' +
    '3LC)5YB\n' +
    'XQQ)DRY\n' +
    'HWQ)27J\n' +
    '4W8)FMF\n' +
    'TN1)VXT\n' +
    '3GJ)FFB\n' +
    'LRP)NPB\n' +
    'LR2)5ZR\n' +
    'ZLJ)5V4\n' +
    'KXN)5QM\n' +
    'TXH)T4W\n' +
    'VNX)9ZB\n' +
    'J47)FPC\n' +
    'D9Y)9M7\n' +
    'MKB)5VF\n' +
    'RMC)VQ3\n' +
    'SVL)Z1C\n' +
    'RGC)S44\n' +
    '8G4)MZ8\n' +
    '6XK)3HJ\n' +
    'R3V)FLX\n' +
    'M6N)Y81\n' +
    'RP3)YVK\n' +
    'C3B)PFW\n' +
    '4LK)GR1\n' +
    '1QQ)6CC\n' +
    '76J)1KP\n' +
    'DYY)QYR\n' +
    'PBQ)7X8\n' +
    'VZV)F15\n' +
    '9F2)ZJN\n' +
    'VBD)6B2\n' +
    '6X5)WXY\n' +
    '23D)SP2\n' +
    'TQ1)TFW\n' +
    'WM1)G1Q\n' +
    '5V4)9NS\n' +
    '2WJ)QQF\n' +
    'ZV7)PYK\n' +
    'MP4)5DD\n' +
    'YC6)KW8\n' +
    'SQ9)XZX\n' +
    'X5Q)6NH\n' +
    '54D)2LN\n' +
    '9NS)X5J\n' +
    '7T8)SRT\n' +
    'V45)7TG\n' +
    'CL7)QDF\n' +
    'XV4)9GF\n' +
    'ZYQ)H8P\n' +
    '5GM)M5Z\n' +
    'QYG)XLH\n' +
    'QLS)29F\n' +
    'TTB)J6F\n' +
    'LGZ)9L7\n' +
    'HTD)C3B\n' +
    '7VD)3Y7\n' +
    'FLQ)GWK\n' +
    'SY9)PN1\n' +
    'BHB)MLX\n' +
    '3X4)G43\n' +
    'CV3)DHF\n' +
    '7DM)HFB\n' +
    'YM9)8W7\n' +
    '3D9)CMT\n' +
    'SKV)64Z\n' +
    'DTY)GGD\n' +
    'HLV)71T\n' +
    'Z6Y)N6H\n' +
    'JB2)73Y\n' +
    'MVG)LGZ\n' +
    'VYV)463\n' +
    'JCS)24L\n' +
    'MCX)5TY\n' +
    'RWQ)9BS\n' +
    'HVV)H4L\n' +
    'CN8)8FJ\n' +
    'YS5)NY2\n' +
    '7CX)67Y\n' +
    '5JY)LFV\n' +
    '3GQ)2K4\n' +
    '433)KY5\n' +
    'FLQ)MQ7\n' +
    '3FR)CSB\n' +
    'TW8)V5Y\n' +
    'TY9)5CG\n' +
    'PWZ)86Z\n' +
    'XTT)3GJ\n' +
    'TM5)X18\n' +
    'NNT)KZV\n' +
    'RX9)DJY\n' +
    'RQS)TN1\n' +
    'S11)TJ4\n' +
    'FTV)KBG\n' +
    '9YC)VCG\n' +
    'B8W)H29\n' +
    '5ZH)2V1\n' +
    'MFH)3MG\n' +
    '92Q)M6C\n' +
    'XSY)QT2\n' +
    '347)614\n' +
    'DLP)BF9\n' +
    'B1L)KRP\n' +
    'NKF)88J\n' +
    'DDN)P4C\n' +
    '2RG)JKJ\n' +
    '5GZ)Q8S\n' +
    'WJK)GTB\n' +
    'RQC)21J\n' +
    'J56)3GZ\n' +
    '25M)SGR\n' +
    'P29)M1W\n' +
    '3FZ)PXR\n' +
    'LLQ)RRJ\n' +
    'NLD)PW6\n' +
    '9R7)Y4X\n' +
    'JCC)6ZZ\n' +
    '96D)1MF\n' +
    'TZV)JJ7\n' +
    '2RN)Q48\n' +
    'Z7G)GD9\n' +
    '85F)JWD\n' +
    'PFW)L9K\n' +
    '6TF)S7G\n' +
    'DV4)9R7\n' +
    'Z9X)R9X\n' +
    'DXD)M6N\n' +
    'KWS)DPK\n' +
    '1R6)Q58\n' +
    '1B2)4LT\n' +
    'D9M)L4Z\n' +
    'JKJ)K4V\n' +
    'P36)V7J\n' +
    'GTZ)W24\n' +
    'GX5)MZ4\n' +
    'H73)QMT\n' +
    'VNG)4SZ\n' +
    '9TV)BD2\n' +
    'CG6)SNS\n' +
    'WD1)HTT\n' +
    '9R3)4L3\n' +
    '7KV)96D\n' +
    '8HW)QHV\n' +
    '85K)HML\n' +
    'B77)BFL\n' +
    'RMB)3WP\n' +
    'MVC)B84\n' +
    '6LJ)N3J\n' +
    'VPH)4NG\n' +
    '14Q)23D\n' +
    'PCB)H1K\n' +
    'RRJ)9KY\n' +
    'W24)VHN\n' +
    'RDN)S54\n' +
    '7ZS)C28\n' +
    'FWZ)FRW\n' +
    '7JQ)NNY\n' +
    '492)CG6\n' +
    'NWC)ZZW\n' +
    'JF2)YY5\n' +
    '6B4)5KN\n' +
    'LZY)JTZ\n' +
    'P3V)4D7\n' +
    'NVT)1MG\n' +
    'SGT)P2M\n' +
    '2NX)WJJ\n' +
    'K6L)64P\n' +
    'KXL)X7Z\n' +
    'R2D)NPQ\n' +
    '33H)P62\n' +
    '7SL)HF4\n' +
    'FYF)GKD\n' +
    'NT5)XN9\n' +
    '6TL)BVZ\n' +
    '5YK)K4B\n' +
    'XDG)347\n' +
    'B2P)8BF\n' +
    'B5Y)8NZ\n' +
    'DDC)TW6\n' +
    'GY6)XYL\n' +
    'T7D)D1Q\n' +
    'MXJ)6D6\n' +
    '6NG)P3P\n' +
    'XSQ)D4T\n' +
    'HY9)RMB\n' +
    'K6L)ND1\n' +
    'RHL)MKB\n' +
    'KRH)QB7\n' +
    'SMS)BBM\n' +
    'DCW)GG2\n' +
    'SMZ)1SY\n' +
    'ZVP)C53\n' +
    'CJJ)ZRB\n' +
    '3VC)RFC\n' +
    'F3V)713\n' +
    '9KM)83Z\n' +
    '18C)22W\n' +
    '7R9)RCX\n' +
    'QMT)Q1R\n' +
    '1VW)J8N\n' +
    'VSD)FWZ\n' +
    'W61)RMC\n' +
    'NQ4)Z61\n' +
    'LTN)KVP\n' +
    'YYK)V5S\n' +
    '1GP)7W6\n' +
    'BJW)RQJ\n' +
    'FRW)5JZ\n' +
    '1JF)KTT\n' +
    'ND1)N6L\n' +
    '69L)R48\n' +
    'TW6)NZC\n' +
    '6VG)RCM\n' +
    'FQR)5Z9\n' +
    'JTD)G9N\n' +
    'SDY)5T3\n' +
    'S33)925\n' +
    '1SY)9SY\n' +
    'QF6)964\n' +
    '2ZH)BTK\n' +
    '1GC)22S\n' +
    'DJT)FCD\n' +
    'SKD)K79\n' +
    'VG1)QRQ\n' +
    'S7S)346\n' +
    '8GP)YZG\n' +
    '25R)1QQ\n' +
    'G4G)RWM\n' +
    'BHW)4JF\n' +
    'DHG)S1S\n' +
    'NJP)L5Z\n' +
    'ZTP)V5B\n' +
    '2K4)8HK\n' +
    'RPQ)KRH\n' +
    'VXT)8TN\n' +
    'BVZ)P3T\n' +
    'HQ8)5GM\n' +
    'C22)PMP\n' +
    '2B2)RH7\n' +
    'PWG)QWH\n' +
    'B45)VP4\n' +
    'RSR)WLL\n' +
    '2RT)1D2\n' +
    'V5Y)ZGH\n' +
    'N3W)ZR9\n' +
    'N46)MD5\n' +
    'CMT)D19\n' +
    'YNF)7CZ\n' +
    '294)ZV9\n' +
    'K4B)NPK\n' +
    '5LP)CXN\n' +
    'BY9)6DF\n' +
    'NZ6)2QM\n' +
    'LRJ)Q25\n' +
    '9ZL)G5B\n' +
    '9VF)GLK\n' +
    'VH8)KJL\n' +
    'PWM)W5W\n' +
    'Z61)3SD\n' +
    'FWZ)1VX\n' +
    'YMZ)4V7\n' +
    'LP7)WZF\n' +
    '3TC)BBV\n' +
    '6QK)58C\n' +
    'W6T)ZCM\n' +
    'LMV)3SG\n' +
    'RXW)X9C\n' +
    'FB3)QXV\n' +
    'SFF)54D\n' +
    '9V5)VDX\n' +
    'ZCX)HR1\n' +
    'J6F)9CT\n' +
    'S7C)FSD\n' +
    '565)YTK\n' +
    'GW5)WSN\n' +
    'JMG)VKV\n' +
    '83Z)MLH\n' +
    'FH1)HJ3\n' +
    'Y3Y)CDW\n' +
    'WJ8)Y4Q\n' +
    '54C)GYZ\n' +
    '46L)4F9\n' +
    'M9B)H6Y\n' +
    'C97)86G\n' +
    'T7D)BHW\n' +
    'SFQ)H2J\n' +
    'Y3W)M44\n' +
    'G1Q)MXZ\n' +
    'M6C)WWR\n' +
    'J76)4JB\n' +
    'H2D)85F\n' +
    'PT6)9VF\n' +
    'KK9)6K7\n' +
    'FM1)QVX\n' +
    'QX7)7X1\n' +
    'X5D)1J2\n' +
    'YXG)VMD\n' +
    'VHP)FTY\n' +
    'P62)X6M\n' +
    'XBT)V45\n' +
    '2PP)GHP\n' +
    'BD2)8BD\n' +
    'HCS)59C\n' +
    '38R)VF7\n' +
    '7NX)SQJ\n' +
    '9YX)1GX\n' +
    'W92)PDC\n' +
    '3TH)WFL\n' +
    '2P8)W6T\n' +
    'H85)693\n' +
    '9NL)CJY\n' +
    'P2M)TRF\n' +
    '35P)8VZ\n' +
    'R2G)2XZ\n' +
    'DRG)LGS\n' +
    'XBC)7JQ\n' +
    'LH1)QNQ\n' +
    'ZR7)ZXG\n' +
    'B5H)S1Q\n' +
    'YG1)LTN\n' +
    'LLY)74V\n' +
    '4RN)Z6Y\n' +
    'P9R)17B\n' +
    'TFW)N4Y\n' +
    'HLS)JZL\n' +
    'XC8)R7L\n' +
    'Z4Q)B5H\n' +
    '6NL)V63\n' +
    'Y5S)T9X\n' +
    'F72)JHN\n' +
    'PDC)DD5\n' +
    'XF4)RXW\n' +
    'QDF)2B2\n' +
    '45M)4J1\n' +
    'WXY)YL8\n' +
    '17N)DRL\n' +
    'L9K)TDM\n' +
    '5NN)84K\n' +
    'J6P)SG1\n' +
    '3L2)366\n' +
    'RVX)WD1\n' +
    'RML)TNL\n' +
    'WJC)7D7\n' +
    '3Y5)DLP\n' +
    '2XZ)9R3\n' +
    'YL8)H3V\n' +
    'WW7)NT5\n' +
    'WP9)9MZ\n' +
    '5GQ)G1H\n' +
    'BR6)ZG6\n' +
    'F48)QF8\n' +
    'J8H)L57\n' +
    '3HJ)6KD\n' +
    'S4M)J9H\n' +
    'P3T)DR2\n' +
    '5BP)DYM\n' +
    'SHH)JTD\n' +
    'TKT)BJJ\n' +
    '9KW)LRC\n' +
    'SGT)Y8D\n' +
    'ZXG)9CP\n' +
    'BSF)LD6\n' +
    '86G)ZD4\n' +
    'NMS)H71\n' +
    'WFH)SP5\n' +
    '5LY)3BB\n' +
    'XJT)51Q\n' +
    'P6P)SMS\n' +
    'WMB)L23\n' +
    '1GX)C34\n' +
    '2MQ)4R5\n' +
    'T66)FPF\n' +
    'ZZ8)6T8\n' +
    'Z88)PBQ\n' +
    '2MS)X1H\n' +
    'MYZ)98J\n' +
    'Q48)JD3\n' +
    'CSN)8J5\n' +
    'XVZ)M6S\n' +
    'FHF)HTN\n' +
    'HCZ)D3V\n' +
    '9JZ)SDL\n' +
    '38P)HQL\n' +
    '9J9)CJK\n' +
    'MPM)M92\n' +
    'N1X)B6Q\n' +
    'ZN5)JW8\n' +
    'JG6)3RK\n' +
    'R2G)TJ3\n' +
    'SKD)HLT\n' +
    'W8R)GBT\n' +
    '58C)RGC\n' +
    'ZCM)26D\n' +
    'MKM)5BP\n' +
    '71T)M1Z\n' +
    'C2M)KNC\n' +
    'SZ2)2YX\n' +
    'XJX)4B3\n' +
    '2BK)76J\n' +
    'XQ6)FZV\n' +
    'VNK)4RS\n' +
    '7MQ)RMS\n' +
    'FCD)34C\n' +
    'TF3)L4F\n' +
    '23D)XJ2\n' +
    'W87)62T\n' +
    '25M)QNS\n' +
    'DDS)VG1\n' +
    'F17)SH4\n' +
    'LL6)5T2\n' +
    'JYP)DFH\n' +
    '5NN)V2X\n' +
    '4R5)Q5V\n' +
    'Q25)Z8H\n' +
    'K6Q)BDR\n' +
    'R2K)PZJ\n' +
    'FP7)2S1\n' +
    'KMN)3VW\n' +
    'ZT8)H9X\n' +
    'W33)43Y\n' +
    '758)R7G\n' +
    '8QB)6LC\n' +
    '6LC)MHQ\n' +
    '88J)GLF\n' +
    'H1K)N12\n' +
    'BTK)DMF\n' +
    'ZG6)TFR\n' +
    'ZPZ)8TT\n' +
    'DJY)LSZ\n' +
    'S1Q)FY1\n' +
    '74K)MVC\n' +
    'B34)9BH\n' +
    '5BP)W1Z\n' +
    'N3W)TLS\n' +
    '1J2)43R\n' +
    '9PG)HLS\n' +
    'Q74)8M5\n' +
    '2GH)6VG\n' +
    'Z5B)B45\n' +
    'L5Z)433\n' +
    'JFC)ZKY\n' +
    'VC1)HT7\n' +
    '229)GW5\n' +
    'QF8)FTC\n' +
    'YB8)THG\n' +
    '55B)27V\n' +
    'DF4)J9R\n' +
    'R7J)2FL\n' +
    'N15)H5C\n' +
    'RZN)5N3\n' +
    'B8C)WBW\n' +
    '7M9)VN2\n' +
    '8T1)7DM\n' +
    'VN9)5KR\n' +
    'FYJ)SKV\n' +
    'MVG)1VL\n' +
    'GRG)ZK2\n' +
    '7HH)3S1\n' +
    'Q85)9PG\n' +
    'BGZ)MK7\n' +
    'H39)P3V\n' +
    '6CF)FLQ\n' +
    'PK6)VYV\n' +
    '9MN)6NP\n' +
    'FY4)PQJ\n' +
    'CR4)LH1\n' +
    '7RL)RSR\n' +
    'JRY)1W6\n' +
    '6RV)R11\n' +
    'MTV)VSD\n' +
    'N26)LWB\n' +
    'C4F)3X4\n' +
    '9BK)LK2\n' +
    'PB3)WQB\n' +
    'JKJ)NWL\n' +
    'BDL)KBT\n' +
    'K35)9F2\n' +
    'WXN)1RD\n' +
    'FK9)XBT\n' +
    'FZT)34D\n' +
    '5SL)B34\n' +
    '6XK)CDV\n' +
    '7XH)7PC\n' +
    'YHM)6VR\n' +
    '7DC)X5D\n' +
    'FL1)3GQ\n' +
    '7FM)67R\n' +
    '6VG)XQQ\n' +
    'W1Z)2JK\n' +
    'Y1V)GZS\n' +
    'R5J)6JY\n' +
    '4YL)ZW2\n' +
    'H2F)7CX\n' +
    'VXQ)HYQ\n' +
    '65V)3CP\n' +
    'KTT)WW7\n' +
    '6V7)T8S\n' +
    'LFR)LP7\n' +
    '5CG)GFB\n' +
    'VCG)LCY\n' +
    'KWY)C48\n' +
    '2YX)JG8\n' +
    '73Y)6F1\n' +
    'QJT)DGK\n' +
    'VJB)Z7G\n' +
    '8NZ)CDB\n' +
    'GXW)18C\n' +
    'WVM)JSX\n' +
    'XLK)9KF\n' +
    'JTD)PT6\n' +
    '8G3)TJ9\n' +
    '67R)YZH\n' +
    'J7G)5VG\n' +
    '4JB)5GK\n' +
    'R6P)7HH\n' +
    'X7Z)N8X\n' +
    'LDL)294\n' +
    'H2J)T11\n' +
    'DZK)XTT\n' +
    '8VZ)HWQ\n' +
    'DZ2)GKV\n' +
    'NTX)FP7\n' +
    '2JK)TTB\n' +
    'FS9)22T\n' +
    'X6D)DC3\n' +
    'LK2)CS3\n' +
    'ZNQ)RPM\n' +
    'TW3)BK4\n' +
    'MLH)NWC\n' +
    '2WN)RVX\n' +
    'M16)BJW\n' +
    'FDR)K6L\n' +
    '7T8)ZWX\n' +
    'RPM)4LK\n' +
    '3F5)BZT\n' +
    'TKK)KJ8\n' +
    '6CR)C5V\n' +
    'XHY)X9T\n' +
    'ZG9)VFJ\n' +
    'D5Z)S82\n' +
    'HJ3)1GP\n' +
    'JD3)BB2\n' +
    'ZKY)6RK\n' +
    '9M6)175\n' +
    'XM7)KSZ\n' +
    'ZZN)R2F\n' +
    '5T2)VY6\n' +
    '1NY)878\n' +
    'GS5)B61\n' +
    'MNS)N6Z\n' +
    'MVF)P74\n' +
    'LR9)PXG\n' +
    '572)229\n' +
    '9GD)HSL\n' +
    'S4N)XBC\n' +
    '283)TRC\n' +
    'SC1)ZCX\n' +
    'HLT)MSD\n' +
    '9M6)SFQ\n' +
    'SJD)RBR\n' +
    '7F7)RPQ\n' +
    'PYG)BPR\n' +
    'X6M)RSH\n' +
    '35P)VSJ\n' +
    'CXN)4QX\n' +
    'GWG)KZQ\n' +
    'SWL)DKK\n' +
    'QHV)1B2\n' +
    'BSC)H2D\n' +
    '1K8)B3G\n' +
    'Z78)LPF\n' +
    'K5Z)7DZ\n' +
    'BXR)HBQ\n' +
    'T8T)LNW\n' +
    'Y2V)3Q9\n' +
    'BPR)HCS\n' +
    'TDM)DHS\n' +
    'MKH)1NJ\n' +
    'T3N)VF2\n' +
    'GNH)BKP\n' +
    'MQ7)74K\n' +
    '4NL)YB8\n' +
    '449)LV3\n' +
    'NXG)WD4\n' +
    'TXX)3L2\n' +
    'PMM)TD9\n' +
    'PYK)1NY\n' +
    '9MZ)CHL\n' +
    'K79)RL1\n' +
    'F3V)XHY\n' +
    'MXM)FYF\n' +
    'V2X)SZR\n' +
    'ZZN)XBJ\n' +
    '2P5)XH9\n' +
    'XYL)4XL\n' +
    'P61)MMF\n' +
    'NWL)P9R\n' +
    '2DQ)1VJ\n' +
    '2G6)2MS\n' +
    'B45)GRG\n' +
    'BB2)JC9\n' +
    'H3J)LLQ\n' +
    'TD9)NJP\n' +
    'PQJ)MT7\n' +
    '5R9)2BM\n' +
    'RFD)WB8\n' +
    '8SP)WGJ\n' +
    'SDC)RY4\n' +
    'ZTJ)PT3\n' +
    '4PQ)VNX\n' +
    '5ZH)BFW\n' +
    '27J)Q62\n' +
    'SG1)XQ6\n' +
    'CHT)6NG\n' +
    'WYV)7FM\n' +
    'TF9)ZP4\n' +
    'K8C)L4N\n' +
    '86G)VQD\n' +
    'GBG)FFH\n' +
    '5N3)TF3\n' +
    '5KR)WQQ\n' +
    'ZLY)KB8\n' +
    'CR2)TCV\n' +
    'ZWX)KMN\n' +
    'DL8)MGQ\n' +
    'PCL)L6H\n' +
    'B1Q)T2G\n' +
    'VNY)WTY\n' +
    'NGL)JBQ\n' +
    'HTN)YML\n' +
    'F8S)L4V\n' +
    'MWR)Z9H\n' +
    'ZGH)7ZS\n' +
    'RJG)QMB\n' +
    '35R)CR2\n' +
    '9PD)P6P\n' +
    '9BH)J56\n' +
    'K9G)P41\n' +
    'K7F)WMP\n' +
    'SYM)K26\n' +
    'XF3)BQF\n' +
    'RY4)N75\n' +
    'XRQ)3NN\n' +
    'X8J)5SL\n' +
    'W6V)ZHV\n' +
    'Y3P)M14\n' +
    'CS3)JRF\n' +
    'LQJ)LYN\n' +
    'V5Y)BRW\n' +
    '8J5)GHH\n' +
    'HFB)JF2\n' +
    'V63)3YQ\n' +
    'GPX)572\n' +
    '6GD)7F7\n' +
    '8HK)B8W\n' +
    '68Y)QGR\n' +
    'ZK2)VL1\n' +
    'QMM)J7G\n' +
    '198)38P\n' +
    'WTY)8RC\n' +
    'WFL)QV2\n' +
    'K6B)TXX\n' +
    '3F2)QF6\n' +
    'QDF)TQL\n' +
    '22T)3KS\n' +
    '8BH)2P8\n' +
    '7WP)VV3\n' +
    '3TH)HM1\n' +
    'CDB)F8C\n' +
    'SMZ)M5J\n' +
    'MWJ)4FL\n' +
    'X4J)8SP\n' +
    'H71)WZC\n' +
    '356)1HX\n' +
    'Y9Z)RLR\n' +
    'M1Z)SDC\n' +
    'L9L)RDN\n' +
    '9PD)GNB\n' +
    'DGK)9TV\n' +
    'DD5)Q5F\n' +
    'XR5)6TF\n' +
    '6NH)SF8\n' +
    '8ZL)SQ9\n' +
    'FFH)K5L\n' +
    '6D6)36R\n' +
    'N7P)5Z3\n' +
    'CDV)BPY\n' +
    'FKR)DTY\n' +
    'J8W)1S2\n' +
    'F7M)HLV\n' +
    '17B)XVZ\n' +
    '9CT)XHF\n' +
    'XL4)GNZ\n' +
    'XZX)M16\n' +
    '1GB)MVG\n' +
    'C92)K5N\n' +
    'Q2W)VLT\n' +
    '54N)S7S\n' +
    'GWK)T1D\n' +
    '6VB)3V6\n' +
    '24L)BMT\n' +
    'VN2)N2G\n' +
    '9RX)SDY\n' +
    '7ZC)4RL\n' +
    'LN5)PK7\n' +
    'BB9)TB5\n' +
    'W4Y)NC8\n' +
    '3SG)PKC\n' +
    'SNS)Q9N\n' +
    'JK3)FB3\n' +
    'HK7)QWB\n' +
    'MJ4)TQ4\n' +
    'GWP)RQT\n' +
    'T4W)9RX\n' +
    'TD9)9ZL\n' +
    'XF3)FYT\n' +
    '4LC)KLH\n' +
    'X6W)69V\n' +
    'WJJ)T52\n' +
    'QB7)G8R\n' +
    '1W6)WQM\n' +
    'QW7)FMY\n' +
    '6GR)1QM\n' +
    'ZMM)9GD\n' +
    'ZV9)9YX\n' +
    '1NJ)HTK\n' +
    'XN9)P1R\n' +
    'G8R)D12\n' +
    'FPC)XSY\n' +
    '6DF)WPZ\n' +
    '87M)ZG9\n' +
    'QV2)DKB\n' +
    'H5C)GDZ\n' +
    'BDR)W2S\n' +
    'C53)3D9\n' +
    'L4F)VB5\n' +
    'V5B)3MR\n' +
    'PZJ)T99\n' +
    'FFB)LRJ\n' +
    '9HZ)G1Z\n' +
    'BBV)2GH\n' +
    '65H)Y9Z\n' +
    'X4J)CHT\n' +
    '3X8)FLB\n' +
    '3F3)T7D\n' +
    'W7Q)9M1\n' +
    'ZT4)FPP\n' +
    'Q5F)QYG\n' +
    'FTV)86Q\n' +
    'JQ5)L95\n' +
    '53H)RH9\n' +
    'PN1)94Z\n' +
    'MT7)3NM\n' +
    'DKD)YRQ\n' +
    'DR5)CVK\n' +
    'LXT)T3N\n' +
    '1D2)RQC\n' +
    '1BK)G87\n' +
    'G95)JK3\n' +
    'P3P)4FP\n' +
    '8DH)TKT\n' +
    'F2K)L1Z\n' +
    'KNC)N1P\n' +
    'PW6)RX9\n' +
    '4SZ)GF8\n' +
    'YVK)2BK\n' +
    'WHR)6RV\n' +
    '8PS)DZ2\n' +
    'KB8)Z3Y\n' +
    '4FP)XP7\n' +
    'Z5Q)46L\n' +
    '6C7)544\n' +
    'VJ6)SK8\n' +
    'VL5)L65\n' +
    '8BF)VZX\n' +
    'S4K)QW4\n' +
    'M4B)G3W\n' +
    'X33)VVD\n' +
    'WSN)GBG\n' +
    'SP5)YXQ\n' +
    '4XL)84M\n' +
    'W5W)Y1Q\n' +
    'S82)68S\n' +
    'HNN)GPY\n' +
    '6LD)X5Q\n' +
    'FPF)JVL\n' +
    '1CY)3Y5\n' +
    'D3F)S6X\n' +
    'WJ8)2WN\n' +
    '26B)YL7\n' +
    '4NF)NDC\n' +
    'Q15)PSF\n' +
    '52T)FM1\n' +
    'VHN)9V5\n' +
    'MSD)TWC\n' +
    '7D7)KYK\n' +
    '175)J71\n' +
    'L4Z)HY9\n' +
    '4HR)BSF\n' +
    'ZMY)TJC\n' +
    'RCM)QRN\n' +
    'HBQ)XJT\n' +
    '64P)ZXS\n' +
    'QDJ)6GD\n' +
    'J71)NSN\n' +
    '3WP)3TH\n' +
    'NPK)Y6M\n' +
    '6XF)4ZL\n' +
    'QT2)MWR\n' +
    'N75)WYV\n' +
    'GFB)S29\n' +
    '62Z)9NL\n' +
    'DXS)GWP\n' +
    '71H)2CT\n' +
    'JWD)FWM\n' +
    'MK3)GVD\n' +
    '9M1)442\n' +
    'SRT)D8M\n' +
    'BRW)P4H\n' +
    'M4H)9BV\n' +
    'ZVD)5GZ\n' +
    'WXP)X33\n' +
    'LPS)Y3P\n' +
    'R9D)RVH\n' +
    'NL6)Y1V\n' +
    'N53)WQ3\n' +
    'SK8)FS9\n' +
    'DY8)52Y\n' +
    'D75)CWF\n' +
    'Q9L)VJH\n' +
    'H4R)KXN\n' +
    '4NG)P29\n' +
    '74G)Z67\n' +
    'GX5)NVT\n' +
    'DHS)ZLY\n' +
    'LM3)ZYQ\n' +
    '9P9)255\n' +
    'KBT)JCS\n' +
    'CVK)Z9X\n' +
    'TCW)F8N\n' +
    'HJY)LC8\n' +
    'KW8)K17\n' +
    'F82)WYZ\n' +
    'D3P)ZVP\n' +
    'SJX)NGL\n' +
    '74V)R2K\n' +
    'LWB)R9D\n' +
    '14J)71N\n' +
    '9BS)43Z\n' +
    '8GP)3F3\n' +
    'QMB)RDW\n' +
    'DR1)RWQ\n' +
    'GY7)BXR\n' +
    '255)RHC\n' +
    'XLJ)3R3\n' +
    'P9C)NMS\n' +
    'KB8)5S5\n' +
    'KLZ)RMG\n' +
    '1WZ)XLJ\n' +
    'W1Z)284\n' +
    'XJ2)DL1\n' +
    'N58)XDG\n' +
    'HYD)B5Y\n' +
    'NDC)RKK\n' +
    '4FL)XSQ\n' +
    'CDL)Q85\n' +
    'C62)WF5\n' +
    '94C)DVP\n' +
    '84T)2YY\n' +
    'ZTD)PJP\n' +
    'S82)DKD\n' +
    '6VR)CBC\n' +
    'M6S)W33\n' +
    '949)MFH\n' +
    '4R5)SWP\n' +
    'J98)XZ7\n' +
    'F8C)JCW\n' +
    'BHX)18F\n' +
    'WC1)KGT\n' +
    '9XW)Z2L\n' +
    'TCW)84X\n' +
    'ZCV)5T7\n' +
    'K6Q)3NT\n' +
    'Q9N)FSS\n' +
    '8TN)VKD\n' +
    'XF4)G56\n' +
    'J5C)LDL\n' +
    'D46)CGG\n' +
    'TJ3)96V\n' +
    'T5H)D8Y\n' +
    'YMN)QJT\n' +
    '1QM)F2K\n' +
    'RWH)KXL\n' +
    'T52)79Y\n' +
    'FSD)KXV\n' +
    'XNX)6CR\n' +
    '713)3TC\n' +
    'NLF)4LR\n' +
    'KY5)H4R\n' +
    'CWF)2CD\n' +
    'X9C)2S9\n' +
    'ZX9)ZQY\n' +
    'JFY)K7H\n' +
    '5HT)Z1L\n' +
    '9TV)HYD\n' +
    '8RC)C77\n' +
    '8MJ)3XG\n' +
    '5L7)7RL\n' +
    'VB4)DV3\n' +
    '3Y3)7WP\n' +
    'HHP)5GQ\n' +
    'XH9)2PP\n' +
    'VF7)GWG\n' +
    'BPY)7ZC\n' +
    'LHY)YNF\n' +
    'PPS)WVK\n' +
    'ZHV)JQF\n' +
    'TKH)B2P\n' +
    'QRN)3FZ\n' +
    '8B8)S7K\n' +
    'T7K)SJD\n' +
    'S7K)YGQ\n' +
    'J8N)R7J\n' +
    '4FL)7XD\n' +
    '648)71B\n' +
    'G56)MPM\n' +
    'P38)68T\n' +
    '5H7)5B9\n' +
    'TWC)PB3\n' +
    'XRV)FK9\n' +
    'WWR)KK9\n' +
    'XK6)F2Q\n' +
    'FYT)7T8\n' +
    'N85)54N\n' +
    '8DZ)45M\n' +
    'G2F)92Q\n' +
    'LCY)ZZ8\n' +
    'PLD)LM3\n' +
    'RQJ)4WJ\n' +
    'J6L)315\n' +
    'Y6M)KY6\n' +
    'C53)3DB\n' +
    'MWT)Y8S\n' +
    'Q62)H2F\n' +
    '6T8)B1J\n' +
    '43Z)5P4\n' +
    '1HX)M8B\n' +
    'TVX)84T\n' +
    '2YB)Q68\n' +
    '36R)V6Q\n' +
    'T9X)YG1\n' +
    '2YY)NQ1\n' +
    '5YP)GFM\n' +
    'QM9)J8H\n' +
    'JG8)16C\n' +
    '5VG)N9H\n' +
    'M16)JST\n' +
    'RJ3)HR2\n' +
    '29J)N6Y\n' +
    '44W)VJ6\n' +
    '9M7)F96\n' +
    'Z67)3RW\n' +
    'WLL)NTX\n' +
    'CSB)4CL\n' +
    'CWP)GGC\n' +
    '84K)W7Q\n' +
    'QNQ)N25\n' +
    'NWR)CSN\n' +
    'J9H)PG5\n' +
    'DFW)K4G\n' +
    'FTC)68Y\n' +
    'VF7)4W8\n' +
    'VXT)2NX\n' +
    'G5B)FH1\n' +
    'DKK)DRG\n' +
    'C77)DJ1\n' +
    'VZ3)XD3\n' +
    'JVC)NRG\n' +
    'FLB)SHH\n' +
    '71T)MP4\n' +
    '9NL)VNV\n' +
    'RDQ)RJJ\n' +
    'GVN)ZT4\n' +
    '84T)MF7\n' +
    'ZP4)4YN\n' +
    'WT2)3LC\n' +
    '4D7)4NF\n' +
    '5S5)9J9\n' +
    'MB6)N9N\n' +
    'MN3)B99\n' +
    'BFL)4XV\n' +
    'BN3)688\n' +
    '5NJ)DPN\n' +
    'XK6)C92\n' +
    'D8M)KWS\n' +
    'RPV)W5S\n' +
    'GX8)FTH\n' +
    'VCT)6Q4\n' +
    'FWM)RDQ\n' +
    '86Z)1M5\n' +
    '46L)JNL\n' +
    'BX1)1R6\n' +
    'DV3)DXQ\n' +
    'JJ7)XFL\n' +
    'K5L)7MQ\n' +
    'X9J)SJX\n' +
    'NNY)MN3\n' +
    'RH9)3DJ\n' +
    'GG2)C2M\n' +
    'JR8)KLZ\n' +
    '8M5)2SN\n' +
    'H9X)BYH\n' +
    'R48)ZZ2\n' +
    'YGQ)55P\n' +
    'BZT)MXJ\n' +
    'N2G)VQJ\n' +
    'VQD)NWR\n' +
    '714)565\n' +
    'Q6W)27Y\n' +
    '3NW)NL6\n' +
    'H6H)F5C\n' +
    '4JF)YM9\n' +
    'D3L)T6S\n' +
    '5QJ)QDJ\n' +
    'QYR)74G\n' +
    'HTT)VB4\n' +
    '9L7)G2F\n' +
    'VVY)BR6\n' +
    'G43)BSC\n' +
    'M8R)S3F\n' +
    'QF6)DCN\n' +
    '2C2)38G\n' +
    'BK4)VL5\n' +
    '6K7)6H7\n' +
    '5TY)96L\n' +
    'JF2)R2G\n' +
    'FLX)7R9\n' +
    'FFX)2MJ\n' +
    'M14)C97\n' +
    '34C)Q6W\n' +
    'HF4)W8T\n' +
    'K7J)TF9\n' +
    '464)4NX\n' +
    'MKW)6VB\n' +
    '1S2)YPG\n' +
    'JK3)1JF\n' +
    '6ZW)WJ8\n' +
    '38G)XNL\n' +
    '7F7)WXP\n' +
    'JST)2ZH\n' +
    'LNM)N26\n' +
    '925)GC9\n' +
    'H29)LHG\n' +
    '5B9)K1Y\n' +
    'ZD4)RH3\n' +
    'NY2)M1R\n' +
    'HF4)2G6\n' +
    '4L6)FKR\n' +
    'H2D)2KN\n' +
    '48L)7SQ\n' +
    'S1T)4YL\n' +
    'DJ1)XL4\n' +
    'B84)1RM\n' +
    '92N)SY9\n' +
    '7X1)MJ3\n' +
    'X32)WVM\n' +
    'TJC)Q1T\n' +
    'YTK)MWQ\n' +
    'WB8)ZV7\n' +
    'H5K)6LD\n' +
    'B66)1BQ\n' +
    '4LB)D3F\n' +
    'Z3Y)SQB\n' +
    '5Z3)2P5\n' +
    'X6L)BNH\n' +
    '7DR)TQ1\n' +
    'SDC)JY4\n' +
    'RPC)SST\n' +
    'DXQ)WCX\n' +
    'WH3)YC6\n' +
    'JTZ)DYY\n' +
    '9TL)QW7\n' +
    'LRP)758\n' +
    'TLS)Y2V\n' +
    'K5N)D75\n' +
    'MWQ)BX1\n' +
    'TRF)VLZ\n' +
    'DYM)PCL\n' +
    'JQF)9T7\n' +
    'D12)JG6\n' +
    '3DB)NQ4\n' +
    'VKD)8BH\n' +
    '7XD)WM1\n' +
    'T99)RKQ\n' +
    '4LJ)RHL\n' +
    'P4C)K66\n' +
    'TWX)4TX\n' +
    'SY9)VJB\n' +
    'L6H)MVF\n' +
    'LV3)1FB\n' +
    '71N)2PL\n' +
    'VFJ)F82\n' +
    '116)95T\n' +
    'VSJ)LR2\n' +
    '6CC)W8R\n' +
    'R84)HNK\n' +
    '4TX)YWC\n' +
    'HTK)82X\n' +
    'P6P)B1G\n' +
    'Z4L)X9J\n' +
    'WVK)HNN\n' +
    'BQF)X6L\n' +
    '734)6V7\n' +
    'LY2)HVV\n' +
    'Y8D)S1T\n' +
    '1SN)4LJ\n' +
    '3KS)6BX\n' +
    '797)GY6\n' +
    'HR2)P6J\n' +
    'NQJ)C4F\n' +
    '3NT)3FR\n' +
    '2PP)Z5Q\n' +
    'F8N)8TY\n' +
    '3GZ)4LB\n' +
    'BJJ)33H\n' +
    'LFV)QL2\n' +
    'TJ8)P9C\n' +
    'QWH)JQ5\n' +
    'KJ8)4KV\n' +
    'C7W)S33\n' +
    'Y4X)FTV\n' +
    'Z2L)JFC\n' +
    'B77)5QJ\n' +
    'N8X)CDL\n' +
    'RQT)HYC\n' +
    '71B)D9M\n' +
    '2LN)LGF\n' +
    'YKR)3MX\n' +
    'H6Y)116\n' +
    'X5J)LBS\n' +
    '2BY)385\n' +
    'N6Z)C98\n' +
    '5GN)9KW\n' +
    '9TC)RQ8\n' +
    'LPS)RBD\n' +
    'T32)YMN\n' +
    'W3J)Z6Z\n' +
    '7CZ)NRV\n' +
    'MGQ)DXS\n' +
    'HQK)2DV\n' +
    'HNW)8ZC\n' +
    'D3L)SYM\n' +
    'H3V)F84\n' +
    'VL1)BY9\n' +
    'LK9)HTD\n' +
    'VHQ)WX5\n' +
    'DR2)W6V\n' +
    '3MX)2BY\n' +
    '2PL)5GV\n' +
    'V5S)R5J\n' +
    'JLB)FL1\n' +
    'TQL)YQM\n' +
    'SWP)2DQ\n' +
    '29F)8DH\n' +
    'W7W)H39\n' +
    'WGJ)5NJ\n' +
    'FQR)P36\n' +
    'PG5)DY8\n' +
    'WZC)F2V\n' +
    'ZJN)Y2X\n' +
    'P6J)N46\n' +
    'RSH)5X7\n' +
    '7K2)PC9\n' +
    '1WY)LDR\n' +
    '3X8)H3J\n' +
    'R7T)LLY\n' +
    'Q1T)QRM\n' +
    '9M7)K8C\n' +
    'R2P)V43\n' +
    'NRV)GKT\n' +
    'SQB)198\n' +
    '2DK)Y5S\n' +
    'JVL)9BY\n' +
    'WPZ)LR9\n' +
    'ZXS)2VP\n' +
    'GY6)JJ6\n' +
    'XD3)3NW\n' +
    'XNL)4N5\n' +
    '86Q)YKR\n' +
    '2FL)1K8\n' +
    'F2D)PSP\n' +
    '16C)LY2\n' +
    'TCV)TCW\n' +
    'JSX)71H\n' +
    'S29)W7W\n' +
    '96L)VX2\n' +
    'YWC)C62\n' +
    '68S)99Q\n' +
    'MZ4)2MX\n' +
    'WCX)9TL\n' +
    'D19)C11\n' +
    '9SY)NNT\n' +
    'K26)RQS\n' +
    'YML)SMZ\n' +
    'K58)6X5\n' +
    'W1B)M4H\n' +
    '3XG)J2R\n' +
    'PMP)V84\n' +
    'Q25)CN8\n' +
    'QWB)K58\n' +
    '284)9BK\n' +
    'RCX)2C2\n' +
    '1SQ)N3D\n' +
    'RFD)TWX\n' +
    '5F6)VN9\n' +
    '22W)WXN\n' +
    'QNS)JBB\n' +
    'GKT)TKK\n' +
    '1WZ)DXG\n' +
    'QZL)VVY\n' +
    '9BK)5YP\n' +
    '1VX)X32\n' +
    'KZQ)5JY\n' +
    'DCN)F8X\n' +
    'Y6M)N58\n' +
    'ZP4)JLB\n' +
    'N9Q)8QB\n' +
    'VL1)QBH\n' +
    'LYN)8M7\n' +
    'V6Q)RZN\n' +
    '2FL)DF4\n' +
    'F48)TNH\n' +
    'MXZ)GXW\n' +
    'M92)YLD\n' +
    'MSD)CWP\n' +
    'F9P)FQR\n' +
    'W8T)R7T\n' +
    'RDW)TY9\n' +
    'HNK)SVL\n' +
    'T3R)JWR\n' +
    'XLH)MBV\n' +
    'KLH)V5Z\n' +
    'WF5)Y3R\n' +
    'GR1)8RT\n' +
    '132)DR1\n' +
    'HTT)4HR\n' +
    '27V)8HW\n' +
    'FSH)WT2\n' +
    'X9J)5YK\n' +
    '1RM)PTQ\n' +
    'DVP)F72\n' +
    '5Z3)BB9\n' +
    'VQ3)WFH\n' +
    'QDB)X3S\n' +
    'F1C)S4M\n' +
    'MK7)PWZ\n' +
    'YL7)Y6R\n' +
    '961)WQ4\n' +
    'GZS)1GC\n' +
    'ZRB)CR4\n' +
    '62T)BGL\n' +
    '4KV)XRQ\n' +
    'GNB)62Z\n' +
    'F9P)TJ8\n' +
    'T93)8DZ\n' +
    '94G)5GN\n' +
    'ND1)NKX\n' +
    '3NM)K6B\n' +
    'QRQ)MK3\n' +
    'GTB)DXD\n' +
    '2CD)XC8\n' +
    'X6M)J9D\n' +
    'CBC)5MV\n' +
    'JCJ)VNT\n' +
    'XBC)RFD\n' +
    'GFM)HNW\n' +
    'DGK)8B5\n' +
    '346)7XH\n' +
    'GF8)GD5\n' +
    'X53)85K\n' +
    'GD5)PMM\n' +
    '83Y)JB2\n' +
    '5Z9)ZXW\n' +
    'BJJ)H85\n' +
    'XR5)KGW\n' +
    'Z9H)YFQ\n' +
    'F58)HPW\n' +
    '9M1)RCK\n' +
    'VV3)3YX\n' +
    '36M)W61\n' +
    'KDR)1SQ\n' +
    '3G9)D3P\n' +
    'CGG)FHB\n' +
    'PKC)3Y8\n' +
    'JJ6)VPH\n' +
    'FSS)ZCV\n' +
    'Z2L)3P9\n' +
    'XLJ)R3V\n' +
    'P93)KQQ\n' +
    'K17)JCC\n' +
    '7DM)TZV\n' +
    'N12)XMC\n' +
    'V7J)MJ4\n' +
    '64F)83Y\n' +
    'S7G)98Y\n' +
    '84M)LSD\n' +
    'KWN)QR2\n' +
    '3W5)F7M\n' +
    'ZW2)QPD\n' +
    'XFL)9MN\n' +
    'MW6)LK9\n' +
    'PMP)XF3\n' +
    'X9T)N9Q\n' +
    'CSN)14Q\n' +
    '3Y8)GY7\n' +
    'DRP)GPJ\n' +
    'LGS)XM7\n' +
    'RBF)QZL\n' +
    'VLZ)Z88\n' +
    '95T)P61\n' +
    'N6H)FHF\n' +
    'WMP)DFW\n' +
    'N6Y)87B\n' +
    '27Y)F8S\n' +
    'QD6)WJC\n' +
    'WD4)J5C\n' +
    'PD6)WGH\n' +
    '4LT)RJG\n' +
    'LPF)BHX\n' +
    'JBQ)D3G\n' +
    'THG)CVX\n' +
    'QWK)G1G\n' +
    'WWS)5HT\n' +
    'D3G)PCB\n' +
    'RMS)FSH\n' +
    '689)69Y\n' +
    'LSZ)F1C\n' +
    '315)FY4\n' +
    'HYC)N7P\n' +
    'G19)MW6\n' +
    '6F1)QX7\n' +
    '6JY)DHG\n' +
    'FWW)F9P\n' +
    'F2Q)7D5\n' +
    '83X)LL6\n' +
    'NH8)WT9\n' +
    'XTG)WP9\n' +
    '4B3)MKM\n' +
    'WQB)TW8\n' +
    '169)R84\n' +
    '4CL)M8R\n' +
    'ZRB)N2B\n' +
    'LD6)Y57\n' +
    'L57)B1Q\n' +
    '8RT)LN5\n' +
    'MJ3)9DW\n' +
    '5MV)55B\n' +
    '3Q9)VHQ\n' +
    'R8Y)F2H\n' +
    '614)734\n' +
    '22S)FF7\n' +
    'W5S)4L6\n' +
    'JHN)6ZW\n' +
    'LDJ)VH8\n' +
    'T11)GVN\n' +
    '2VP)FZT\n' +
    '6H7)2QF\n' +
    'SDL)VCT\n' +
    '94Z)5J9\n' +
    'TDH)FYJ\n' +
    'R6J)F2D\n' +
    'KPS)T8T\n' +
    'L6H)HQK\n' +
    '5ZR)14J\n' +
    'HML)648\n' +
    'M1W)Q2W\n' +
    'MVV)169\n' +
    'QPD)CV3\n' +
    'QVX)LHY\n' +
    'WC8)RLH\n' +
    '51Q)8T2\n' +
    '8GF)J76\n' +
    'W92)PPS\n' +
    '96V)R6P\n' +
    'ZZ2)WPN\n' +
    '442)92Y\n' +
    '2S1)K35\n' +
    'TB5)7TM\n' +
    '43Y)949\n' +
    'F2H)JMG\n' +
    'K4V)DQ6\n' +
    'JY4)R3X\n' +
    'GD5)7KF\n' +
    'MZ8)DRP\n' +
    'BK5)KDR\n' +
    'CJK)HQ8\n' +
    'Y88)WJK\n' +
    'GLF)H73\n' +
    'PSF)94C\n' +
    'Y79)17K\n' +
    'LNW)LDJ\n' +
    'TNH)N15\n' +
    'MBV)K9G\n' +
    'VB5)SAN\n' +
    '6X7)RPV\n' +
    '54Z)SFF\n' +
    '3P9)R2P\n' +
    'YLD)961\n' +
    'GPJ)PK6\n' +
    'M5J)BNZ\n' +
    'N3J)8CH\n' +
    'YXQ)PWM\n' +
    'TNL)KL2\n' +
    'JWR)D5Z\n' +
    'Z8B)N53\n' +
    'QRM)WH3\n' +
    'N1P)36M\n' +
    '714)64F\n' +
    '92Q)W49\n' +
    'GGD)8HP\n' +
    'PK7)FLN\n' +
    'K7H)CKT\n' +
    '9V5)DDS\n' +
    'Y8S)R2D\n' +
    'F8X)N3W\n' +
    'S1S)DR5\n' +
    '99R)4NL\n' +
    'R3X)5ZH\n' +
    '79Y)8V7\n' +
    'V43)1B9\n' +
    '2S1)H6H\n' +
    '8TT)9PD\n' +
    'PXG)7SL\n' +
    '9DW)DGZ\n' +
    '7X1)F1F\n' +
    '3V6)YXG\n' +
    'QKF)HJY\n' +
    '2DK)2FC\n' +
    'SQJ)DDC\n' +
    '4LR)S38\n' +
    'MJ1)KTK\n' +
    'J9R)F48\n' +
    'Q1R)F58\n' +
    'FTY)QKF\n' +
    'P1R)1WZ\n' +
    '34D)XTG\n' +
    'QY8)LXT\n' +
    'MT7)Z4Q\n' +
    'SXQ)Q74\n' +
    '8B5)BN3\n' +
    'HVV)XF4\n' +
    'TJ9)W1B\n' +
    '64Z)NXG\n' +
    'BFW)9KM\n' +
    '2QM)35H\n' +
    'NPQ)X53\n' +
    'NGL)VNY\n' +
    'F7M)J6L\n' +
    'M8B)W87\n' +
    '3CP)LPS\n' +
    '4QX)1RL\n' +
    'BKP)D9Y\n' +
    '8W7)FYK\n' +
    'Y62)3Y3\n' +
    'Q68)6X7\n' +
    'CJY)35R\n' +
    '8V7)ZPZ\n' +
    'L4V)B2T\n' +
    'FLN)1VW\n' +
    'S38)83X\n' +
    'RH7)9JZ\n' +
    'TQ4)6B3\n' +
    'P89)MCX\n' +
    'SP2)RBF\n' +
    'ZMX)DL8\n' +
    'BMT)6LB\n' +
    'PXR)1GB\n' +
    '8ZC)B8C\n' +
    '3BB)MXM\n' +
    '43R)W92\n' +
    'Z8H)8GF\n' +
    'LSD)1KD\n' +
    'GD9)VHP\n' +
    'GHP)356\n' +
    'KZY)Y3W\n' +
    'GC9)JYP\n' +
    'FZV)5L7\n' +
    '1RL)2DK\n' +
    '35H)XJX\n' +
    '5GM)C7W\n' +
    '5DD)ZTJ\n' +
    '6LB)SC1\n' +
    '693)T3R\n' +
    'FY1)4PQ\n' +
    'QL2)TMP\n' +
    'DGZ)ZXM\n' +
    '1B9)T96\n' +
    '43Z)492\n' +
    'C98)Z5B\n' +
    'L95)K6Q\n' +
    '3MG)YS5\n' +
    '366)ZJJ\n' +
    'B6P)XV4\n' +
    'J6D)TM5\n' +
    '6NP)Z8B\n' +
    '4XV)53H\n' +
    '4B3)SWL\n' +
    '1VL)CJJ\n' +
    'F2V)5NN\n' +
    'XBJ)DDN\n' +
    'B3G)W3J\n' +
    '7TG)KZY\n' +
    '4V7)VNK\n' +
    'W9D)9YC\n' +
    '4J1)VZ6\n' +
    'M5Z)94G\n' +
    'Y1Q)DV4\n' +
    'KZY)ZLJ\n' +
    '7KF)TSB\n' +
    'GKH)JVC\n' +
    'FLB)1SN\n' +
    'DRY)8PS\n' +
    'WT9)T5H\n' +
    '69Y)8G3\n' +
    '7G4)S11\n' +
    'QQF)QM9\n' +
    '8FJ)1BK\n' +
    'HSL)TFP\n' +
    'LHG)LZY\n' +
    'VJB)2WJ\n' +
    'XSL)GX8\n' +
    'P74)XR9\n' +
    '2V1)52T\n' +
    'WGH)69L\n' +
    'L1Z)J98\n' +
    'VNV)HCZ\n' +
    'NG6)NLF\n' +
    'RBR)X4J\n' +
    'X18)35P\n' +
    'LBS)HK3\n' +
    '7TM)NG6\n' +
    '1RD)25R\n' +
    '6BX)29J\n' +
    'BNH)VF1\n' +
    'QXV)797\n' +
    'M1R)X6D\n' +
    '3R3)6CF\n' +
    '7D5)1WY\n' +
    'MHQ)B6P\n' +
    'MW3)XZK\n' +
    'G3W)LP6\n' +
    '16C)NLD\n' +
    '9ZB)SXQ\n' +
    '2MX)K5Z\n' +
    '3Z2)7K2\n' +
    'JLP)CL7\n' +
    '17K)VXQ\n' +
    'FFB)G91\n' +
    'RFC)48L\n' +
    'TMP)9HZ\n' +
    'T6S)Y79\n' +
    'DVP)283\n' +
    'CHL)QD6\n' +
    'ZJJ)LFR\n' +
    'R2F)N85\n' +
    'HT7)KWN\n' +
    '3YX)W4Y\n' +
    'BGL)K74\n' +
    '5T3)287\n' +
    'Z1L)ZNQ\n' +
    'C28)MW3\n' +
    '385)MNS\n' +
    'GGC)6FJ\n' +
    'YRQ)8T1\n' +
    '5F6)Z4L\n' +
    '8TY)5R9\n' +
    'LC8)132\n' +
    '688)BHB\n' +
    '55P)TDH\n' +
    'K74)GTZ\n' +
    'VZX)714\n' +
    'N1X)2RG\n' +
    'MMF)26B\n' +
    'DV4)G4G\n' +
    'R9X)Z78\n' +
    'RVH)B66\n' +
    'LSZ)XR5\n' +
    'TC1)6XK\n' +
    '98Y)LQJ\n' +
    '83D)BWG\n' +
    'NC8)D3L\n' +
    'BDT)6GR\n' +
    'SH4)SKD\n' +
    '7SQ)T1S\n' +
    'NKF)87M\n' +
    '5KN)FFX\n' +
    'DFH)TC1\n' +
    '8T2)F17\n' +
    'D8Y)5H7\n' +
    'C34)H1V\n' +
    'HM1)ZZN\n' +
    'N25)T66\n' +
    '3VW)GNH\n' +
    'RL1)N1X\n' +
    'YN6)5F6\n' +
    'GKD)1JZ\n' +
    '18F)JLP\n' +
    'PQJ)6TL\n' +
    'Z78)MTV\n' +
    'BBM)ZMY\n' +
    'B1G)Y88\n' +
    'JC9)NKF\n' +
    'QNS)7DR\n' +
    '463)8MJ\n' +
    '3MR)GPX\n' +
    'ZXW)PLD\n' +
    'BF9)7G4\n' +
    'ZKY)Z5L\n' +
    'QGR)MWJ\n' +
    'NSN)SWD\n' +
    'C5V)3Z2\n' +
    'VDX)M3Z\n' +
    'ZR9)K7F\n' +
    '2BM)RPC\n' +
    'GYH)QY8\n' +
    'JBB)6QK\n' +
    'G9N)B77\n' +
    'RPC)M9B\n' +
    'F84)B1L\n' +
    '1JZ)G95\n' +
    'SND)8G4\n' +
    'D1Q)J6D\n' +
    'N9N)LNM\n' +
    'YZH)V8R\n' +
    'TJ4)ZVD\n' +
    '2V1)BGZ';
